# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
Parameters:
  KeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: "The name of the key pair to be used"
    Default: "Adapt-KeyPair"
  AmiId:
    Type: "AWS::EC2::Image::Id"
    Description: Identifier of new AMI to be deployed
  Version:
    Type: "String"
    Description: Version of the software deployed
  Subnets:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: A list of subnets for the Auto Scaling group
  InstanceType:
    Type: "String"
    Description: "Instance Type for running the instances"
    Default: "t3.micro"
  IAMInstanceProfile:
    Type: "String"
    Description: "Instance profile for running the instances"
    Default: "Adapt-Github-BuildImgEC2InstanceProfile-9aCfgCP6X2hv"
  SecurityGroupId:
    Type: "String"
    Description: "Enter the security group id to be used"
    Default: "sg-957b20a9"
Resources:
  # Metadata around AMI to roll it out to a Development environment
  # using an AutoScalingGroup
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${AWS::StackName}-Template"
      LaunchTemplateData:
        ImageId: !Ref AmiId
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref SecurityGroupId
        IamInstanceProfile:
          Name: !Ref IAMInstanceProfile
        UserData: !Base64 |
          #!/bin/bash -x
          systemctl start mongod.service
          cd /home/ec2-user/sourcecode/
          node server
        InstanceType: !Sub "${InstanceType}"
        BlockDeviceMappings:
          - DeviceName: "/dev/xvda"
            Ebs:
              DeleteOnTermination: true
              Encrypted: true
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Application
                Value: !Sub
                  - "${ShortName}"
                  - ShortName: !Select [0, !Split ["-", !Ref AWS::StackName]]
              - Key: Name
                Value: !Sub
                  - "${ShortName} version ${Version}"
                  - ShortName: !Select [0, !Split ["-", !Ref AWS::StackName]]
              - Key: Version
                Value: !Sub "${Version}"
          - ResourceType: volume
            Tags:
              - Key: Application
                Value: !Sub
                  - "${ShortName}"
                  - ShortName: !Select [0, !Split ["-", !Ref AWS::StackName]]
              - Key: Name
                Value: !Sub
                  - "${ShortName} version ${Version}"
                  - ShortName: !Select [0, !Split ["-", !Ref AWS::StackName]]
  # AutoScalingGroup used as Development Environment for rolling out
  # the newly created AMI
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: "1"
      MaxSize: "3"
      # Please REMOVE the next line if you want to avoid interfering
      # with existing capacity in the ASG
      DesiredCapacity: "1"
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier: !Ref Subnets
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 1
        MaxBatchSize: 2
        PauseTime: PT10S
